### ISSUE TITLE
Could this method be applied to Mixture Gaussian testing?

### ISSUE THREAD

**Issue by winerholiday** [oscarkey/composite-tests#1]
Hi~ your code helps me a lot! I want to know how this model applies to  test  Mixture Gaussian.I am a little confused about dist_family = MyModel. How should I define this? Thank you !

**Comment by oscarkey** [comment]
hey! Sorry for the delay, I was on holiday.

You could probably apply the test to a mixture of Gaussians by using the MMD test, using an optimizer to fit the model to the data. This is the same approach that we use for the "toggle switch" model, which is included as an example in the repo, so I would start by modifying that. You can see how the test is implemented for the toggle switch [here](https://github.com/oscarkey/composite-tests/blob/main/src/composite_tests/distributions/toggle_switch.py), and how it is used [here](https://github.com/oscarkey/composite-tests/blob/main/experiments/exp_toggle_switch_increasing_T.py#L131).

However, have you considered using a test developed specifically for mixtures of Gaussians? These tests are likely to have higher power than this test. From a quick look I found [this paper](https://www.sciencedirect.com/science/article/pii/S0167947323001263), which also reviews some of the other tests in this area.
